### PR TITLE
New features and bug fixes

### LINKED ISSUE #23: Should handle if 'conditionalFilter' is null
Hi,

If the 'conditionalFilter' in the question is null blank screen appears. Mentioning the error below,
`getQuestions onResponse : Attempt to read from field 'java.util.ArrayList com.getcloudcherry.survey.model.FilterBy.filterquestions' on a null object reference`

### PR DESCRIPTION
**Pull request by madhurtewani**
- Bug fixes #23 
- New features #24 and #25 
- New feature to provide style while initialising SDK

### CODE REVIEW

File: src/main/java/com/getcloudcherry/survey/httpclient/APIHelper.java [hunk 1]
```diff
@@ -10,7 +10,7 @@
 public class APIHelper {
 
     public static final String GET_QUESTIONS = "SurveyByToken/{token}/{deviceId}";
-    public static final String POST_ANSWER_PARTIAL = "PartialSurvey/{id}/{complete}";
+    public static final String POST_ANSWER_PARTIAL = "PartialSurvey/{id}/{complete}/InApp-Droid";
```
Comment (Femilshajin) [inline src/main/java/com/getcloudcherry/survey/httpclient/APIHelper.java:13]: 'InApp-Droid' Should be added in RecordAnswer.java aswell.
`private static final String DEVICE_ID = "InApp-Droid";`

Comment (madhurtewani) [reply src/main/java/com/getcloudcherry/survey/httpclient/APIHelper.java:13]: @Femilshajin, change has been done.
